# Generated by Django 3.2.15 on 2024-05-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visuwallsproducts', '0003_auto_20240521_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField(default=0)),
                ('booked_quantity', models.IntegerField(default=0)),
                ('rental_quantity', models.IntegerField(default=0)),
                ('damaged_quantity', models.IntegerField(default=0)),
                ('need_repairing_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='visuwallsproducts.product')),
            ],
        ),
    ]
