# Generated by Django 3.2.15 on 2024-05-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visuwallsproducts', '0005_bookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_date', models.DateTimeField(auto_now_add=True)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_booking', to='visuwallsproducts.bookingrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visuwallsproducts.product')),
            ],
        ),
    ]
