# Generated by Django 3.2.15 on 2024-05-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visuwallsproducts', '0012_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
