# Generated by Django 5.0.6 on 2024-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuwallsproducts", "0016_imageupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="productimages/default.png", upload_to="productimages/"
            ),
        ),
    ]
