# Generated by Django 5.0.6 on 2024-06-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuwallsproducts", "0018_bookingrequest_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="dynamic_attributes",
            field=models.JSONField(default=dict),
        ),
    ]
