# Generated by Django 5.0.6 on 2024-06-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuwallsproducts", "0021_alter_confirmbooking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKING_APPROVED", "Booking Approved"),
                    ("SEND_PRODUCT_TO_USER", "Send Product to User"),
                    ("RECEIVED_PRODUCT_BY_USER", "Received Product by User"),
                    ("RETURNED", "Returned"),
                ],
                default="BOOKING",
                max_length=50,
            ),
        ),
    ]
