# Generated by Django 3.2.15 on 2024-05-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in Kg', null=True)),
                ('size', models.CharField(blank=True, help_text='Size in mm', max_length=255)),
                ('pitch', models.CharField(blank=True, max_length=255)),
                ('power_consumption', models.CharField(blank=True, max_length=255)),
                ('brightness', models.CharField(blank=True, max_length=255)),
                ('viewing_angle', models.CharField(blank=True, max_length=255)),
                ('curve', models.CharField(blank=True, max_length=255)),
                ('n_16a_2500w', models.CharField(blank=True, help_text='N/16A(2500w)', max_length=255)),
                ('n_link', models.CharField(blank=True, help_text='N/Link', max_length=255)),
                ('screens_inside_flight_case', models.IntegerField(blank=True, null=True)),
                ('flight_case_dimensions', models.CharField(blank=True, help_text='Flight Case Dimensions (mm)', max_length=255)),
                ('flight_case_weight', models.FloatField(blank=True, help_text='Flight Case Weight in kg', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
