# Generated by Django 3.2.15 on 2024-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64-encoded image', null=True),
        ),
    ]
