# Generated by Django 3.2.15 on 2024-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240516_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('availible', 'Availible'), ('booked', 'Booked'), ('damage', 'Damage'), ('need_repairing', 'Need Repairing'), ('sold', 'Sold')], default='availible', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
