# Generated by Django 3.2.15 on 2024-05-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_confirmbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmbooking',
            name='user',
        ),
    ]
