# Generated by Django 3.2.15 on 2024-05-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_confirmbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbooking',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
